### PR TITLE
Added support to render controls above outputs

### PR DESCRIPTION
**Pull request by wpitallo**

### CODE REVIEW

**Comment by Ni55aN** [comment]
`renderAboveOutputs` option and new template is overcomplicated and in many cases this feature is needless.

Such a feature must be added via custom Node.vue

**Comment by wpitallo** [comment]
Ok, cool. How do you add or use a custom Node.vue without updating the package?

**Comment by Ni55aN** [comment]
Examples:

https://github.com/retejs/rete.js.org/blob/master/src/components/Examples/list/customization/index.js
https://github.com/retejs/rete.js.org/blob/master/src/rete/components/ecosystem/package/component.js

**Comment by wpitallo** [comment]
Ahh, got it thanks so much, appreciate the help! Awesome piece of code BTW!

**Comment by wpitallo** [comment]
You might still want to add the commonjs plugin to rete.config.js if you are having build errors with the latest version of rollup

**Comment by Ni55aN** [comment]
I'll check it asap

**Comment by Ni55aN** [comment]
This error also occurred for me after I reinstalled the dependencies.

**Comment by Ni55aN** [comment]
You can update to [v0.3.4](https://www.npmjs.com/package/rete-vue-render-plugin/v/0.3.4)

**Pull request closed without merging**
