### PR TITLE
feat: support vue3

### PR DESCRIPTION
**Pull request by carl-jin**

### CODE REVIEW

**Comment by rebbort** [comment]
How can you build a plugin? I cloned PR and am trying to build with npm run build but get various errors. Is there any way to get an already assembled plugin?

**Comment by carl-jin** [comment]
> How can you build a plugin? I cloned PR and am trying to build with npm run build but get various errors. Is there any way to get an already assembled plugin?

It looks a little bit hard, if u wanna build a plugin to hack with this problem, I'm not sure the Author is still alive or not or he just forgot his pwd. 

but here is my solution, replace rete.min.js during the Deploy processing 

``` javascript
//   ./index.js

const { exec, spawn, execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

function log(msg) {
  console.log(`deploy: ${msg}`);
}

log('update node_modules');
let installCMD = exec(`npm install`, { cwd: path.resolve(__dirname, '../') });
installCMD.stdout.pipe(process.stdout);
installCMD.stderr.pipe(process.stderr);
installCMD.on('exit', function () {
  //  replace rete.esm.js
  log('replace ete.esm.js');
  let targetFile = path.resolve(__dirname, '../', 'node_modules/rete/build/rete.esm.js');
  let sourceFile = path.resolve(__dirname, './rete.esm.js');
  fs.writeFileSync(targetFile, fs.readFileSync(sourceFile));

  log('npm run build');
  let buildCMD = exec(`npm run build:no-cache`, { cwd: path.resolve(__dirname, '../') });
  buildCMD.stdout.pipe(process.stdout);
  buildCMD.stderr.pipe(process.stderr);
  buildCMD.on('exit', function () {
    log('start deploy');
    process.exit();
  });
});

```

**Comment by Ni55aN** [comment]
@carl-jin ~~I'm unable to build the plugin with these changes even after updating rollup and rollup vue plugin~~

```
(node:9553) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (10:13) in /home/ni55an/Workflow/retejs/vue-render-plugin/src/Node.vue?vue&type=script&lang.js
    at Parser.pp$4.raise (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16954:13)
    at Parser.pp.unexpected (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:14462:8)
    at Parser.pp.expect (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:14456:26)
    at Parser.pp$2.parseBindingList (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:15682:17)
    at Parser.pp$3.parseMethod (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16719:22)
    at Parser.pp$3.parsePropertyValue (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16641:23)
    at Parser.pp$3.parseProperty (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16626:8)
    at Parser.pp$3.parseObj (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16572:21)
    at Parser.pp$3.parseExprAtom (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16307:17)
    at Parser.pp$3.parseExprSubscripts (/home/ni55an/Workflow/retejs/vue-render-plugin/node_modules/rollup/dist/shared/rollup.js:16126:19)
    ```

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/513#issuecomment-892944094

**Comment by Ni55aN** [comment]
[1.0.0-rc1](https://www.npmjs.com/package/rete-vue-render-plugin/v/1.0.0-rc1) is published. Based on these changes with a couple of fixes

**Comment by Ni55aN** [comment]
in the thread https://github.com/retejs/vue-render-plugin/issues/39 you can find more information

**Pull request closed without merging**
